pipeline{
    agent{
        docker{
            image 'node:lts-buster-slim'
            args '-p 5000:5000'
        }
    }
    environment{
        CI='true'
    }
    stages{
        stage('Node.js builed') {
            steps {
                sh 'cd backend && npm install'
            }
        }
        
        stage('React builed') {
            steps {
                 sh 'cd frontend && npm install'
            }
        }

        stage('tests') {
            steps {
                sh 'cd frontend && npm run test'
            }
        }
        
        stage('Deploy to Render') {
            steps {
                // Install the Render CLI
                sh 'curl -sL https://render.com/install.sh | bash'
                
                // Build the React application
                sh 'npm install'  // Install dependencies
                sh 'npm run build'  // Build the React app
                
                // Deploy the Node.js server and React application to Render
                sh 'render deploy --build-command "npm install && npm run build" --start-command "npm start"'
            }
        }

    }
}
