pipeline{
    agent{
        docker{
            image 'node:lts-buster-slim'
            args '-p 5000:5000'
        }
    }
    environment{
        CI='true'
    }
    stages{
        stage('build'){
            steps{
                sh "pwd"
                sh "cd backend"
                sh "npm start server"
            }
        }
    }
}