pipeline{
    agent{
        docker{
            image 'node:lts-buster-slim'
            args '-p 5000:5000'
        }
    }
    environment{
        CI='true'
    }
    stages{
        stage('Node.js builed') {
            steps {
                sh 'cd backend && npm install'
            }
        }
        
        stage('React builed') {
            steps {
                 sh 'cd frontend && npm install'
            }
        }

        stage('tests') {
            steps {
                sh 'cd frontend && npm run test'
            }
        }
        
        stage('Deploy to Render') {
            steps {
                sh 'render deploy --name team12 --path frontend'
                sh 'render deploy --name team12-api --path backend'
            }
        }
    }
}
